---
name: test.yml
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run check
        run: |
          make lint
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'
      - name: run unit tests
        run: |
          make depend
          make unit
          go tool cover -html coverprofile.out -o coverage-report.html
      - uses: actions/upload-artifact@v4
        with:
          name: 'coverage-report'
          path: coverage-report.html
